# Site settings
title: Suzanne Daniels
description: 'Business Card Page'
url: 'http://suuu.us'
baseurl: ''
profilepic: '/images/suuscrop.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '5faeb3c48c.js'

author:
  name: 'Suzanne Daniels'
  email: suzanne@daniels.cc
  twitter_username: suushier
#  facebook_username: joshgerdes
  github_username:  suuus
  linkedin_username:  suzannedaniels
  # meetup_name: VACD

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
