# Site settings
title: 'suuu.us | Suzanne Daniels'
tagline: 'Code. Music. Gayness.'
description: 'This is the website of Suzanne Daniels'
url: 'http://suuu.us'
baseurl: ''
profilepic: '/images/suuscrop.jpg'
bkimage: '/images/bk2.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '5faeb3c48c.js'
title_image: 'http://suuu.us/images/bk2.jpg'

author:
  name: 'Suzanne Daniels'
  email: suzanne@daniels.cc
  twitter: suushier
  picture: '/images/suuscrop.jpg'
  twitter_username: suushier
#  facebook_username: joshgerdes
  github_username:  suuus
  linkedin_username:  suzannedaniels
  # meetup_name: VACD
  sessionize_name: suzannedaniels
  mixcloud_name: suuuus

twitter:
    username: suushier
    card: summary

social:
    name: Suzanne Daniels
    links:
      - https://twitter.com/suushier
      - https://www.linkedin.com/in/suzannedaniels
      - https://github.com/suuus

plugins:
  - jekyll-readme-index
  - jekyll-seo-tag

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: false

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
